import { ProductImages } from "./ProductImage";
import { Product } from "../../../../../reducers/cycles/reducer";


export const products: Product[] = [
    {
        id: "01",
        productName: "Expresso Tradicional",
        description: "O tradicional café feito com água quente e grãos moídos",
        price: 10,
        image: ProductImages.ExpressoTradicional,
        tags: ["Tradicional"],
        quantity: 0,
    },
    {
        id: "02",
        productName: "Expresso Americano",
        description: "Expresso diluído, menos intenso que o tradicional",
        price: 5,
        image: ProductImages.ExpressoAmericano,
        tags: ["Tradicional"],
        quantity: 0,
    },
    {
        id: "03",
        productName: "Expresso Cremoso",
        description: "Café expresso tradicional com espuma cremosa",
        price: 9.90,
        image: ProductImages.ExpressoCremoso,
        tags: ["Tradicional"],
        quantity: 0,
    },
    {
        id: "04",
        productName: "Expresso Gelado",
        description: "Bebida preparada com café expresso e cubos de gelo",
        price: 9.90,
        image: ProductImages.ExpressoGelado,
        tags: ["Tradicional", "Gelado"],
        quantity: 0,
    },
    {
        id: "05",
        productName: "Café com Leite",
        description: "Meio a meio de expresso tradicional com leite vaporizado",
        price: 9.90,
        image: ProductImages.CafeComLeite,
        tags: ["Tradicional", "Com Leite"],
        quantity: 0,
    },
    {
        id: "06",
        productName: "Latte",
        description: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
        price: 9.90,
        image: ProductImages.Latte,
        tags: ["Tradicional", "Com Leite"],
        quantity: 0,
    },
    {
        id: "07",
        productName: "Capuccino",
        description: "Bebida com canela feita de doses iguais de café, leite e espuma",
        price: 9.90,
        image: ProductImages.Capuccino,
        tags: ["Tradicional", "Com Leite"],
        quantity: 0,
    },
    {
        id: "08",
        productName: "Macchiato",
        description: "Café expresso misturado com um pouco de leite quente e espuma",
        price: 9.90,
        image: ProductImages.Macchiato,
        tags: ["Tradicional", "Com Leite"],
        quantity: 0,
    },
    {
        id: "09",
        productName: "Mocaccino",
        description: "Café expresso com calda de chocolate, pouco leite e espuma",
        price: 9.90,
        image: ProductImages.Mocaccino,
        tags: ["Tradicional", "Com Leite"],
        quantity: 0,
    },
    {
        id: "10",
        productName: "Chocolate Quente",
        description: "Bebida feita com chocolate dissolvido no leite quente e café",
        price: 9.90,
        image: ProductImages.ChocolateQuente,
        tags: ["Especial", "Com Leite"],
        quantity: 0,
    },
    {
        id: "11",
        productName: "Cubano",
        description: "Drink gelado de café expresso com rum, creme de leite e hortelã",
        price: 9.90,
        image: ProductImages.Cubano,
        tags: ["Especial", "Alcoólico", "Gelado"],
        quantity: 0,
    },
    {
        id: "12",
        productName: "Havaiano",
        description: "Bebida adocicada preparada com café e leite de coco",
        price: 9.90,
        image: ProductImages.Havaiano,
        tags: ["Especial"],
        quantity: 0,
    },
    {
        id: "13",
        productName: "Árabe",
        description: "Bebida preparada com grãos de café árabe e especiarias",
        price: 9.90,
        image: ProductImages.Arabe,
        tags: ["Especial"],
        quantity: 0,
    },
    {
        id: "14",
        productName: "Irlandês",
        description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
        price: 9.90,
        image: ProductImages.Irlandes,
        tags: ["Especial", "Alcoólico"],
        quantity: 0,
    }
    
]
